language: node_js

node_js:
  - "7"

before_script:
  - npm run deploy

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "dist"
  on:
    branch: master

notifications:
  email: false