language: node_js

node_js:
  - "8"

before_script:
  - npm run deploy

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "dist"
  repo: "flid-it/flid-it.github.io"
  target_branch: "master"
  on:
    branch: master

notifications:
  email: false